# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug_w32
endif
export config

PROJECTS := mousehide

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

mousehide: 
	@echo "==== Building mousehide ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f mousehide.make

clean:
	@${MAKE} --no-print-directory -C . -f mousehide.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug_w32"
	@echo "   release_w32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mousehide"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
